version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pylint
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pylint store-data.py
            pylint get-data.py
      - store-test-results:
          path: test-reports
