name: VulnerabilityScan

on:
  workflow_dispatch:
#  毎月1日のUTC15:00(JST00:00)にスキャン
#  schedule:
#  - cron:  '0 0 15  '
#  push:
#    branches:
#    - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: リポジトリCheckout
      id: checkout
      uses: actions/checkout@v2

    - name: Hadolint 静的解析
      id: hadolint
      uses: brpaz/hadolint-action@master

    - name: イメージビルド
      id: build
      run: |
        TAG=test:securitycheck
        docker build -f Dockerfile -t ${TAG} .
        echo "::set-output name=tag::${TAG}"
    - name: Dockle イメージスキャン
      uses: hands-lab/dockle-action@master
      with:
        image: ${{ steps.build.outputs.tag }}

    - name: Trivy イメージスキャン
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.build.outputs.tag }}
        ignore-unfixed: true
        format: 'table'
        severity: 'CRITICAL,HIGH'
